### ISSUE TITLE
Put Card - Date with Time

### ISSUE THREAD

**Issue by neyStyle** [uhppoted/uhppoted#2]
Hey,

I use Uhppoted by nodeRed and it works perfect. We use 20 diffrent 4 Door Controller and import and export everything
in a mySql Database on our Server and build our own Backend to manage everything.

It is possible to add a Hour for the putCard node ?
We only can set the Date but it was better when we can set the Time also.

Thank you very much

**Comment by uhppoted** [comment]
Wow! Nice system!!

re. `putCard`. Unfortunately the limitation is imposed by the actual controller - it only supports dates for the `from` and `to` fields. 

But maybe take a look at _time profiles_, which allow for much finer grained access. The specific functions/nodes are:
- `clear-time-profiles`
- `get-time-profile`
- `set-time-profile`

Each time profile allows up to 3 time periods during which a card has access and can also be defined as active between dates and on specific days of the week. Profiles can also be chained to create fairly complex schedules - you may need get a bit creative though, depending on what you're trying to achieve :-).

There's a very basic example [here](https://github.com/uhppoted/node-red-contrib-uhppoted/blob/master/examples/basic/9-time-profiles.json) and the _info_ documentation for the nodes describes the format. The description is a fairly minimal - let me know if you need any additional information.

**Comment by uhppoted** [comment]
Ok, great! Hopefully that works for you :-).

I guess as a fallback you could update the controller whenever a card's access changes e.g. if it's due to expire at 16:30 then at 16:30 you actively change the card record on the controller. But if _time profiles_ can do what you want they're a much better solution.

The controller also provides an API to allow for remote access control - it's not implemented in any of the _uhppoted_ components at the moment but I'll start looking into it. Although TBH, as far as I can tell it's only intended for very complicated access control requirements (e.g. the Fred can only access a room if Tom is there and Jane is not kind of thing). _Time profiles_ and _tasks_ should suffice for most day-to-day requirements.

**Comment by neyStyle** [comment]
Oh fine,

i will try this and will see what is the best workaround.
At this moment we have on Apartment House for rent with 22 Apartments and Saune etc.... 
Every Apartment has Chip-Card´s for open.
But we have on every Door a QR-Reader for a Chip and a QR-Code. At this moment we programming Apple Passkit that we can send the Guest a Pass for her Wallet, works fine. For all People without a Apple Divice we send also a PDF with the QR-Code. it works really good.

**Comment by uhppoted** [comment]
Neat system! Out of curiosity, what readers are you using? I'd like to add them to my 'tried-and-tested' hardware list - I'm slowly building up a list of "_known to work_" components for the "_do you know if this will work?_" type questions that occasionally crop up.

**Comment by neyStyle** [comment]
Hey we use this Reader: 
https://www.i-keys.de/de/zutrittskontrollsysteme/qr-code-zugangskontrolle-mit-rfid-reader-iso14443.html?c=91

i have open it and insider in the case ist this reader:
https://www.ico.de/newland-fm430l-u-barracuda-2d-fixmount-usb-kabel-wechselbar--bcpf6u?referer=froogle&gclid=Cj0KCQjwkIGKBhCxARIsAINMioJ4fxcqv9W3dINBdnEwEUjRJIBHhXoQfJMO5wL4uKlf902Gm8--FBkaAi3vEALw_wcB

**Comment by uhppoted** [comment]
Awesome! Thank you :-)

**Comment by uhppoted** [comment]
Hi,

I've updated the compatible hardware list with the readers and am going to close this out - don't think there's any more I can add to the above. Feel free to reopen if you need to though :-).
