### ISSUE TITLE
Is it for me?? 

### ISSUE THREAD

**Issue by rvt** [uhppoted/uhppoted#5]
Hey,

we have two wiegang controllers where apparently the windows software expired/license stopped working..

we now have to log in into two seperate controllers to add/remove users... uhppoted make for us a userinterface into two controllers and beable to control our doors, look into logs and add/remove users?

**Comment by adamskobel** [comment]
This setup is more technical and allows you to do more with your controller, so you could use it. If your desire is to use the software that came with it, the registration code is 2004, it should have been on the box when you purchased the device. There is no separate licensing of the software.

**Comment by uhppoted** [comment]
Thanks Adam! Nice to know you're still around :-).

@rvt, Adam is correct in that the core components of this software are intended for integration with other systems. However, over time it has acquired a couple of _stock integrations_, one of which may meet your needs:

- [uhppote-cli](https://github.com/uhppoted/uhppote-cli) can integrate one or more controllers with almost anything that can be scripted using (e.g. I've used it with bash and sqlite)
- [uhppoted-app-s3](https://github.com/uhppoted/uhppoted-app-s3) integrates one or more controllers with a file based access control list
- [uhppoted-app-sheets](https://github.com/uhppoted/uhppoted-app-sheets) integrates one or more controllers with an access control list that is managed on Google Sheets.
- [uhppoted-app-wild-apricot](https://github.com/uhppoted/uhppoted-app-wild-apricot) which integrates one or more controllers with a membership list managed by [Wild Apricot](https://www.wildapricot.com)

There is also an a [web based interface](https://github.com/uhppoted/uhppoted-httpd) that is in development - but you'd have to be feeling brave and experimental because it is still very much under active development and has quite a way to go before it's production ready.

If you can give me some idea of what you're looking for I can perhaps point you in the right direction?

**Comment by uhppoted** [comment]
Oh, one other thing, the minimum firmware version supported is v6.56. If your controllers are very old they may not have the required onboard support.

**Comment by uhppoted** [comment]
Closing - no further activity.

**Comment by rvt** [comment]
No problem of being closing, due to work quite busy (this is for our clubhouse...) if I have question, I will let you know!

thanks for the info

**Comment by uhppoted** [comment]
No worries - feel free to reopen if you need to :-)
